spring:
  datasource:
    url: jdbc:h2:mem:test # H2
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false # Show SQL
    hibernate:
      ddl-auto: create-drop # Set database Schema
    properties:
      hibernate:
        format_sql: true # Pretty print the SQL
  data:
    mongodb:
      database: check-app # MongoDB
      port: 27017
